book_requests/urls.py
from django.urls import path
from . import views
"""
URL configuration for library_reviews project.

The `urlpatterns` list routes URLs to views.
"""

urlpatterns = [
    path('book_requests.html', views.request_view, name='book_requests'),
]

library_reviews/urls.py
"""
URL configuration for library_reviews project.

The `urlpatterns` list routes URLs to views.
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("reviews.urls"), name="reviews-urls"),
    path("", include("book_requests.urls"), name="book_requests-urls"),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
]

reviews/urls.py
from . import views
from django.urls import path
"""
URL configuration for library_reviews project.

The `urlpatterns` list routes URLs to views.
"""
urlpatterns = [
    path('', views.BookList.as_view(), name='home'),
    path('<slug:slug>/', views.book_details, name="book_details"),
    path('<slug:slug>/edit_review/<int:review_id>',
         views.review_edit, name='review_edit'),
    path('<slug:slug>/delete_review/<int:review_id>',
         views.review_delete, name='review_delete'),
]

book_requests/models.py
from django.db import models


# This model captures and stores user book requests
class Request(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    what_book_would_you_like_to_request = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.what_book_would_you_like_to_request

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))


# Model designed to represent a book with essential information
# Such as title, author, a blurb, a URL to buy the book
class Book(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.CharField(max_length=200)
    blurb = models.TextField(blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    featured_image = CloudinaryField('image', default='placeholder')
    buy_here = models.URLField(max_length=128, blank=False)


# Model designed to store and manange reviews of books
# Each review is linked to a specific book with an approval status
class Reviewed(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name="reviews")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="book_details"
        )
    body = models.TextField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"Review {self.body} by {self.author}"

book_requests/forms.py
from django import forms
from .models import Request


# Generates a book request box
class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['name', 'email', 'what_book_would_you_like_to_request']

reviews/forms.py
from .models import Reviewed
from django import forms
from django.core.exceptions import ValidationError


# Generates a Review form box
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviewed
        fields = ('body',)

book_requests/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RequestForm


def request_view(request):
    """
    Handle the display and processing of the book request form.

    This view handles both displaying the empty form (for GET requests)
    and processing form submissions (for POST requests).

    **Context:**
    - If the request method is POST, it processes the submitted form data.
      If the form is valid, it saves the request to the database and
      adds a success message for the user.
    - If the request method is GET, it simply displays an empty form.

    **Template:**
    - `book_requests/book_requests.html`

    **Messages:**
    - On successful form submission: "Book request received! I will try
    getting this loaded ASAP!"
    """
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Book request received! I will try getting this loaded ASAP!.")
    else:
        form = RequestForm()

    return render(request, 'book_requests/book_requests.html', {'form': form})

reviews/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Book, Reviewed
from .forms import ReviewForm


# Create your views here.
class BookList(generic.ListView):
    model = Book
    queryset = Book.objects.all().order_by("id")
    template_name = "reviews/index.html"
    paginate_by = 6


def book_details(request, slug):
    """
    Display an individual :model:`reviews.Book`.

    **Context**

    ``book``
        An instance of :model:`reviews.Book`.

    **Template:**

    :template:`reviews/book_details.html`
    """

    queryset = Book.objects.filter(status=1)
    book = get_object_or_404(queryset, slug=slug)
    reviews = book.reviews.all()
    review_count = book.reviews.filter(approved=True).count()

    if request.method == "POST":
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.author = request.user
            review.book = book

            if request.user.is_staff:
                # Automatically approved if the user is an admin
                review.approved = True
                messages.add_message(
                    request, messages.SUCCESS,
                    'Review submitted and approved!'
                )
            else:
                # Review goes to admin to approve if the user is not staff
                review.approved = False
                messages.add_message(
                    request, messages.SUCCESS,
                    'Review submitted and awaiting approval'
                )

            review.save()

            # Re-fetch all reviews after saving the new one
            reviews = book.reviews.all()

    review_form = ReviewForm()

    return render(request, 'reviews/book_details.html', {
        'book': book,
        'reviews': reviews,
        'review_count': review_count,
        'review_form': review_form
    })


def review_edit(request, slug, review_id):
    """
    View to edit reviews
    """
    if request.method == "POST":

        queryset = Book.objects.filter(status=1)
        book = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Reviewed, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        if review_form.is_valid() and review.author == request.user:
            review = review_form.save(commit=False)
            review.book = book

            # Automatically approved if the user is an admin
            if request.user.is_staff:
                review.approved = True
                messages.add_message(request, messages.SUCCESS,
                                     'Review updated and approved!')
            else:
                # Edited review goes to admin to approve if user is not staff
                review.approved = False
                messages.add_message(request, messages.SUCCESS,
                                     'Review updated, approval pending!')

            review.save()
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating review!')

    return HttpResponseRedirect(reverse('book_details', args=[slug]))


def review_delete(request, slug, review_id):
    """
    view to delete review
    """
    queryset = Book.objects.filter(status=1)
    book = get_object_or_404(queryset, slug=slug)
    review = get_object_or_404(Reviewed, pk=review_id)

# If user is the author they can delete their own review
    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS,
                             'Review deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete your own review!')

    return HttpResponseRedirect(reverse('book_details', args=[slug]))

book_requests/templates/book_requests/book_requests.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-6 my-5">
        <h2>Give us a book request to add!</h2>
        <p>Requesting a novel allows you to explore unique 
            stories and voices that might not be available 
            locally. It can introduce you to new genres, 
            perspectives, and authors, enriching your reading 
            experience and expanding the diversity of narratives 
            in your library or bookstore. Plus, it supports 
            the demand for varied literary works, ensuring 
            that compelling stories continue to reach readers.
        </p>

        <!-- Form block -->
        <form method="post" id="form-block">
            {{ form | crispy }}
            {% csrf_token %}
            <button class="btn btn-secondary" type="submit">Submit
            </button>
        </form>
    </div>
</div>
{% endblock %}

reviews/templates/reviews/book_details.html
{% extends 'base.html' %} {% block content %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="masthead-text">
                <!-- Book title goes in these h1 tags -->
                <h1 class="book-title">{{ book.title }}</h1>
                <!-- Book author goes before the | the book's created date goes after -->
                <p class="book-subtitle"><i>By {{ book.author }}</i></p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="d-block d-md-block col-md-4">
            {% if "placeholder" in book.featured_image.url %}
            <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
            {% else %}
            <img class="card-img-top" src=" {{ book.featured_image.url }}" alt="{{ book.title }}">
            {% endif %}
        </div>
        <div class="col-md-6 card mb-4  mt-3 left  top" id="book-detail-blurb">
            <div class="card-body">
                <!-- The book content goes inside the card-text. -->
                <p>
                    {{ book.blurb | safe }}
                </p>
                <a href="{{ book.buy_here }}" target="_blank" class="btn btn-primary">Buy Here</a>
            </div>
        </div>
    </div>
    <!-- Displaying count of reviews -->
    <div class="row">
        <div class="col-12">
            <strong class="text-secondary">
                <i class="far fa-reviews"></i>This book currently has {{ review_count }} review(s)
            </strong>
        </div>
        <div class="col-12">
            <hr>
        </div>
    </div>
    <!-- Displaying reviews -->
    <div class="row">
        <div class="col-md-6 card mb-4  mt-3 ">
            <h3>Reviews:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags
          to iterate through each review in reviews -->
                {% for review in reviews %}
                <div class="p-2 reviews
          {% if not review.approved and review.author == user %}
          faded{% elif not review.approved %} d-none{% endif %}">
                    <p class="font-weight-bold">
                        {{ review.author }} wrote:
                    </p>
                    <div id="review{{ review.id }}">
                        {{ review.body | linebreaks }}
                    </div>
                    {% if not review.approved and review.author == user %}
                    <p class="approval">
                        This review is awaiting approval
                    </p>
                    {% endif %}
                    {% if user.is_authenticated and review.author == user %}
                    <button class="btn btn-delete" review_id="{{ review.id }}">Delete</button>
                    <button class="btn btn-edit" review_id="{{ review.id }}">Edit</button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <!-- Creating New reviews -->
        <div class="col-md-6 card mb-4 mt-3">
            <div class="card-body">
                {% if user.is_authenticated %}
                <h3>Leave a review:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form id="reviewForm" method="post" style="margin-top: 1.3em;">
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <p><a href="{% url 'account_login' %}">Log in</a> or <a href="{% url 'account_signup' %}">Sign up</a> to
                    leave a review</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete review?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your review?
                This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block extras %}
<script src="{% static 'js/reviews.js' %}"></script>
{% endblock %}

reviews/templates/reviews/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Book Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                <div class="col-md-1"></div>
                {% for book in book_list %}
                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-body">
                            <a href="{% url 'book_details' book.slug %}" class="book-link">
                                <div class="image-container book-thumbnail">
                                    {% if "placeholder" in book.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                        alt="placeholder image">
                                    {% else %}
                                    <img class="card-img-top" src=" {{ book.featured_image.url }}" alt="{{ book.title }}">
                                    {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ book.author }}</p>
                                    </div>
                                </div>
                                <div class="book-details">
                                    <h2 class="card-title">{{ book.title }}</h2>
                                    <p class="card-text">{{ book.blurb }}</p>
                                </div>
                            </a>

                            <hr>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> &laquo; PREVIOUS</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

templates/base.html
{% url 'home' as home_url %}
{% load static %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'book_requests' as book_requests_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Gaurav's Book Reviews</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/default.jpg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="brand" href="{% url 'home' %}">
                <span>
                    Reviewed
                    <i class="fas fa-book-open"></i>
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == book_requests_url %}active{% endif %}" aria-current="page"
                            href="{% url 'book_requests' %}">Book Requests</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
          fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% if user.is_authenticated %}
        <p class="text-end m-3">You are logged in as {{ user }}</p>
        {% else %}
        <p class="text-end m-3">You are not logged in</p>
        {% endif %}

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">
            {% block madeby %}
            Made by Gaurav Jagpal
            {% endblock %}
        </p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
        </script>
    {% block extras %}
    {% endblock %}

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}